### ISSUE TITLE
push some stack problems

### ISSUE THREAD

**Issue by asaurav22** [oops-aman/Data-Structures#2]

**Comment by ansi11290** [comment]
assign to me

**Comment by saishubham468** [comment]
Hi @oops-aman  can you assign this to me after @ansi11290 does it. I can add another another problem after that

**Comment by asaurav22** [comment]
Ok

**Comment by saishubham468** [comment]
Hi I have added the application to stacks with which you can convert infix expression to postfix. PR #7 . @oops-aman
